/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import listas.*;

/**
 *
 * @author LUIS POTTE
 */
public class VerCategoria extends javax.swing.JDialog {

    String NombreDeCategoria;
    Multilista aux;

    /**
     * Creates new form VerCategorias
     */
    public VerCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public VerCategoria(java.awt.Frame aThis, boolean b, String prod, Multilista stock) {
        super(aThis, b);
        initComponents();
        this.NombreDeCategoria = prod;
        this.aux = stock;
        this.setLocationRelativeTo(null);
        this.modelo();
    }

    public JLabel getNom_cate() {
        return nom_cate;
    }

    public void setNom_cate(JLabel nom_cate) {
        this.nom_cate = nom_cate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom_cate = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Elementos de la categoria");

        nom_cate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nom_cate.setForeground(new java.awt.Color(204, 0, 0));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2cancelar(evt);
            }
        });

        TablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Categoria", "SubCategoria", "Referencia", "Cantidad "
            }
        ));
        jScrollPane2.setViewportView(TablaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nom_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nom_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2cancelar
        this.dispose();
    }//GEN-LAST:event_jButton2cancelar

    public void setNombreDeCategoria(Object NombreDeCategoria) {
        this.NombreDeCategoria = (String) NombreDeCategoria;
    }

    private void mostar_datos(DefaultTableModel tabla, int n, int m) {
        DefaultTableModel Tabla = (DefaultTableModel) TablaInfo.getModel();
        System.out.println("Entró a mostraar datos"+ NombreDeCategoria);
        NodoPrincipal cats = aux.getNodo(NombreDeCategoria);
        System.out.println(": " + cats.getInfo());
        //imprimo todos los productos de las subcategorias que se hicieron en la categoria
        NodoSegundario subnodo = cats.getNodos().getInicio();
        while (subnodo != null) {
            NodoSegundario u = (NodoSegundario) subnodo.getInfo();
            System.out.println("  " + u.getInfo()); // nombre de la sublista
            u = u.getSiguiente();
            int row = 0, column = 0;
            while (u != null) {
                System.out.println("entró a porductos info");
                // informacion del producto
                Producto infoProducto = (Producto) u.getInfo();
                tabla.setValueAt(infoProducto.getCategoria(), row, column);
                column++;
                tabla.setValueAt(infoProducto.getCantidad(), row, column);
                column++;
                tabla.setValueAt(infoProducto.getNombre(), row, column);
                column++;
                tabla.setValueAt(infoProducto.getReferencia(), row, column);
                column++;
                tabla.setValueAt(infoProducto.getSubcategoria(), row, column);
                column++;
                u = u.getSiguiente();
                row++;
                column = 0;
            }
            subnodo = subnodo.getSiguiente();
        }
        TablaInfo.setModel(tabla);
    }
    
    private void modelo(){
        DefaultTableModel ModeloTabla = (DefaultTableModel) TablaInfo.getModel();
        System.out.println("Entró a mostraar datos"+ NombreDeCategoria);
        NodoPrincipal cats = aux.getNodo(NombreDeCategoria);
        System.out.println(": " + cats.getInfo());
        //imprimo todos los productos de las subcategorias que se hicieron en la categoria
        NodoSegundario subnodo = cats.getNodos().getInicio();
        int contR=0, contC=5; 
        while (subnodo != null) {
            NodoSegundario u = (NodoSegundario) subnodo.getInfo();
            System.out.println("  " + u.getInfo()); // nombre de la sublista
            u = u.getSiguiente();
            int filas = 0, colum = 0;
            while (u != null) {
                contR++;
                u = u.getSiguiente();
            }
            subnodo = subnodo.getSiguiente();
        }
        
        ModeloTabla.setRowCount(contR);
        ModeloTabla.setColumnCount(contC);
        mostar_datos(ModeloTabla, contR, contC);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCategoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCategoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCategoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCategoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerCategoria dialog = new VerCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInfo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nom_cate;
    // End of variables declaration//GEN-END:variables

}
