/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import listas.Multilista;
import listas.NodoPrincipal;
import listas.NodoSegundario;

/**
 *
 * @author LUIS POTTE
 */
public class VerStock extends javax.swing.JDialog {

    Multilista aux;

    /**
     * Creates new form VerStock
     */
    public VerStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VerStock(java.awt.Frame parent, boolean modal, Multilista Stock) {
        super(parent, modal);
        initComponents();
        this.aux = Stock;
        this.setLocationRelativeTo(null);
        this.modelo();
    }

    private void mostar_datos(DefaultTableModel tabla, int n, int m) {
        DefaultTableModel Tabla = (DefaultTableModel) TablaInfo.getModel();
        NodoPrincipal cats = aux.getInicioMulti();
        int row = 0, column = 0;
        while (cats != null) {
            NodoSegundario subnodo = cats.getNodos().getInicio();
            while (subnodo != null) {
                NodoSegundario u = (NodoSegundario) subnodo.getInfo();
                u = u.getSiguiente();
                while (u != null) {
                    // informacion del producto
                    Producto infoProducto = (Producto) u.getInfo();
                    tabla.setValueAt(infoProducto.getReferencia(), row, column);
                    column++;
                    tabla.setValueAt(infoProducto.getCategoria(), row, column);
                    column++;
                    tabla.setValueAt(infoProducto.getSubcategoria(), row, column);
                    column++;
                    tabla.setValueAt(infoProducto.getPrecio(), row, column);
                    column++;
                    tabla.setValueAt(infoProducto.getCantidad(), row, column);
                    column++;
                    u = u.getSiguiente();
                    row++;
                    column = 0;
                }
                subnodo = subnodo.getSiguiente();
            }
            cats = cats.getSiguiente();
        }
        TablaInfo.setModel(tabla);
    }

    private void modelo() {
        DefaultTableModel ModeloTabla = (DefaultTableModel) TablaInfo.getModel();
        NodoPrincipal cats = aux.getInicioMulti();
        int contR = 0, contC = 5;
        while (cats != null) {
            NodoSegundario subnodo = cats.getNodos().getInicio();
            while (subnodo != null) {
                NodoSegundario u = (NodoSegundario) subnodo.getInfo();
                System.out.println("  " + u.getInfo()); // nombre de la sublista
                u = u.getSiguiente();
                int filas = 0, colum = 0;
                while (u != null) {
                    contR++;
                    u = u.getSiguiente();
                }
                subnodo = subnodo.getSiguiente();
            }
            cats = cats.getSiguiente();
        }
        ModeloTabla.setRowCount(contR);
        ModeloTabla.setColumnCount(contC);
        mostar_datos(ModeloTabla, contR, contC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInfo = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ElEMENTOS EN EXISTENCIA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referencia", "Categoria", "SubCategoria", "Precio", "Cantidad "
            }
        ));
        jScrollPane1.setViewportView(TablaInfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 40, 560, 308));

        jButton4.setText("Cancelar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4cancelar(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 406, 90, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel2)
                .addContainerGap(208, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(479, 479, 479))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4cancelar
        this.dispose();
    }//GEN-LAST:event_jButton4cancelar

    public void modelar() {
        DefaultTableModel ModeloTabla = (DefaultTableModel) TablaInfo.getModel();
        int contR = 0, contC = 1;
        int clm = 1;
        // cada producto se va a ir agregando a una columna
        while (clm <= 5) {

        }
        String line;
        Boolean sw = false;
//        while (br.ready()) {
//            line = br.readLine();
//            for (int i = 0; i < line.length(); i++) {
//                if (line.substring(i, i + 1).equals(";")) {
//                    if (!sw) {
//                        contC++;
//                    }
//                }
//            }
//            sw = true;
//            contR++;
//        }
//        ModeloTabla.setRowCount(contR);
//        ModeloTabla.setColumnCount(contC);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerStock dialog = new VerStock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInfo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
