/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import listas.ListaSimple;
import listas.NodoPrincipal;
import listas.NodoSegundario;

/**
 *
 * @author LUIS POTTE
 */
public class VerVentas extends javax.swing.JDialog {

    ListaSimple ventas;

    /**
     * Creates new form VerVentas
     */
    public VerVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VerVentas(java.awt.Frame parent, boolean modal, ListaSimple lis) {
        super(parent, modal);
        initComponents();
        this.ventas = lis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ventas Registradas");

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3cancelar(evt);
            }
        });

        TablaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Referencia", "Categoria", "SubCategoria", "Precio", "Cantidad "
            }
        ));
        jScrollPane1.setViewportView(TablaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3cancelar
        this.dispose();
    }//GEN-LAST:event_jButton3cancelar

//    private void mostar_datos(DefaultTableModel tabla, int n, int m) {
//        DefaultTableModel Tabla = (DefaultTableModel) TablaInfo.getModel();
//        NodoPrincipal cats = aux.getInicioMulti();
//        int row = 0, column = 0;
//        while (cats != null) {
//            NodoSegundario subnodo = cats.getNodos().getInicio();
//            while (subnodo != null) {
//                NodoSegundario u = (NodoSegundario) subnodo.getInfo();
//                u = u.getSiguiente();
//                while (u != null) {
//                    // informacion del producto
//                    Producto infoProducto = (Producto) u.getInfo();
//                    tabla.setValueAt(infoProducto.getReferencia(), row, column);
//                    column++;
//                    tabla.setValueAt(infoProducto.getCategoria(), row, column);
//                    column++;
//                    tabla.setValueAt(infoProducto.getSubcategoria(), row, column);
//                    column++;
//                    tabla.setValueAt(infoProducto.getPrecio(), row, column);
//                    column++;
//                    tabla.setValueAt(infoProducto.getCantidad(), row, column);
//                    column++;
//                    u = u.getSiguiente();
//                    row++;
//                    column = 0;
//                }
//                subnodo = subnodo.getSiguiente();
//            }
//            cats = cats.getSiguiente();
//        }
//        TablaInfo.setModel(tabla);
//    }

//    private void modelo() {
//        DefaultTableModel ModeloTabla = (DefaultTableModel) TablaInfo.getModel();
//        int contR = 0, contC = 5;
//        NodoSegundario subnodo = ventas.getInicio();
//        while (subnodo != null) {
//            contR++;
//            subnodo = subnodo.getSiguiente();
//        }
//        ModeloTabla.setRowCount(contR);
//        ModeloTabla.setColumnCount(contC);
//        mostar_datos(ModeloTabla, contR, contC);
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerVentas dialog = new VerVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInfo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
