
import java.net.Socket;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Estudiantes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     *
     */
    static String contrasen;

    public Login() throws IOException {

        initComponents();
        botonInicio.setBackground(new java.awt.Color(214, 177, 161));
        contrasena.setBackground(null);
        this.setLocationRelativeTo(null);
        contrasen = getContrasena();
        jButton1.setToolTipText("recupera tu contraseña a través de correo electrónico.");
    }

    public static String getContrasena() throws FileNotFoundException, IOException {
        String password = null;
        File v = new File("pass.txt");
        try (FileReader fr = new FileReader(v); BufferedReader br = new BufferedReader(fr)) {
            String line;
            while (br.ready()) {
                line = br.readLine();
                password = line;
            }
        }
        return password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        con = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        contrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        botonInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        linea = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        con.setText("Diosesamorgmmm99");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contrasena.setBorder(null);
        contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrasenaMouseClicked(evt);
            }
        });
        jPanel1.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 220, 310));

        botonInicio.setBackground(new java.awt.Color(214, 177, 161));
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonInicioMouseMoved(evt);
            }
        });
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
        });
        botonInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Iniciar Sesión");
        botonInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 10));

        jPanel1.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 190, 30));

        linea.setBackground(new java.awt.Color(214, 177, 161));
        linea.setForeground(new java.awt.Color(214, 177, 161));
        jPanel1.add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 220, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32306402.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -310, 570, 690));
        jPanel1.add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 210, 20));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Olvidé mi contraseña");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acua.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 410, 400, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 653));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited
        botonInicio.setBackground(new java.awt.Color(232, 190, 168));
    }//GEN-LAST:event_botonInicioMouseExited

    private void botonInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseMoved
        botonInicio.setBackground(new java.awt.Color(214, 177, 161));
    }//GEN-LAST:event_botonInicioMouseMoved

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        err.setText("");
        if (contrasena.getText().equals(contrasen)) {
            try {
                Menú_principal mn = new Menú_principal();
                mn.setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            if (contrasena.getText().equals("")) {
                err.setText("*Por favor digite la contraseña");

            } else {
                err.setText("*Contraseña errónea");
                contrasena.setText("");
            }
        }   // TODO add your handling code here:

    }//GEN-LAST:event_botonInicioMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void contrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaMouseClicked
        linea.setBackground(Color.yellow);
        
    }//GEN-LAST:event_contrasenaMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        linea.setBackground(new java.awt.Color(214, 177, 161));   // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Socket s = new Socket("www.gmail.com", 80);
            if (s.isConnected()) {
                Correo c = new Correo("gbrielamonsalve@gmail.com", "-Recuperación de Contraseña | Accesorios Herrera -", "do.not.reply.aher@gmail.com", "aherrera", contrasen);
                try {
                    c.SendMail(numerosAutenticacion());
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (IOException e) {
           JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión a Internet", "Error de autenticación",JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed
//    public static String Username = "do.not.reply.aher@gmail.com";
//    public static String PassWord = "aherrera";
//    String To = "gbrielamonsalve@gmail.com";
//    String Subject = "-Recuperación de Contraseña | Accesorios Herrera -";

    public String numerosAutenticacion() {
        Integer a, b, c, d;
        a = (int) (Math.random() * 9);
        b = (int) (Math.random() * 9);
        c = (int) (Math.random() * 9);
        d = (int) (Math.random() * 9);
        String i = a.toString() + b.toString() + c.toString() + d.toString();
        System.out.println(i);
        return i;
    }

//    public void SendMail(String coda) throws IOException {
//        String Mensage = "¡Hola!: Es una pena que hayas olvidado tu contraseña, pero no te preocupes, digita el siguiente código en el programa para recuperar tu contraseña: "
//                + "  "
//                + "  " + coda + "  "
//                + " Recuerda: cambiar tu contraseña a menudo permite que tengas mayor seguridad.";
//        String respuesta;
//        Properties props = new Properties();
//        props.put("mail.smtp.auth", "true");
//        props.put("mail.smtp.starttls.enable", "true");
//        props.put("mail.smtp.host", "smtp.gmail.com");
//        props.put("mail.smtp.port", "587");
//        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
//        Session session = Session.getInstance(props,
//                new javax.mail.Authenticator() {
//            @Override
//            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
//                return new javax.mail.PasswordAuthentication(Username, PassWord);
//            }
//        });
//
//        try {
//
//            Message message = new MimeMessage(session);
//            message.setFrom(new InternetAddress(Username));
//            message.setRecipients(Message.RecipientType.TO,
//                    InternetAddress.parse(To));
//            message.setSubject(Subject);
//            message.setText(Mensage);
//            Transport.send(message);
//            JOptionPane.showMessageDialog(this, "Se ha enviado un número de autenticación a tu correo electrónico");
//            respuesta = JOptionPane.showInputDialog(null, "Escribe tu nombre");
//            confirm(respuesta, coda);
//        } catch (MessagingException e) {
//            throw new RuntimeException(e);
//        }
//    }
//
//    public void confirm(String respuesta, String coda) throws IOException {
//        if (respuesta != null) {
//            if (respuesta.equals(coda)) {
//                JOptionPane.showMessageDialog(this, "Su contraseña es: " + contrasen);
//            } else {
//                JOptionPane.showMessageDialog(this, "Fallo en la autenticación, vuelva a intentarlo", "Error de Atenticación", JOptionPane.ERROR_MESSAGE);
//            }
//
//        } else {
//            System.out.println("jeje");
//        }
//
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Login().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonInicio;
    private javax.swing.JPasswordField con;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel err;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator linea;
    // End of variables declaration//GEN-END:variables
}
