/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LUIS POTTE
 */
import Ventanas.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Stock extends javax.swing.JPanel {
    Menú_principal Menú;
    /**
     * Creates new form Stock
     */
    public Stock(Menú_principal p) {
        initComponents();
        this.Menú = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("AGREGAR NUEVA CATEGORIA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7add_nuevacategoria(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 40));

        jButton8.setText("VER PRODUCTOS POR CATEGORIA");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8VerCategorias(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 220, 40));

        jButton2.setText("ELIMINAR PRODUCTOS DEL STOCK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2eliminar_productos(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 220, 40));

        jButton3.setText("AGREGAR UN NUEVO  PRODUCTO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3add_producto(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 240, 40));

        jButton4.setText("AGREGAR NUEVA SUBCATEGORIA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4add_subCategoria(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 220, 40));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Cerrar Stock");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5Salir(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 23, -1, -1));

        jLabel6.setText("STOCK");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 50, 30));

        jButton6.setText("VER TODOS LOS PRODUCTOS EN STOCK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6verTodoElStock(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7add_nuevacategoria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7add_nuevacategoria
        categoria add =new categoria (Menú, true);
        add.setVisible(true);
    }//GEN-LAST:event_jButton7add_nuevacategoria

    private void jButton8VerCategorias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8VerCategorias
        String prod = JOptionPane.showInputDialog("Digite el nombre de la categria que desea ver");
        VerCategoria vcat = new VerCategoria (Menú, true, prod);
        vcat.setVisible(true);
    }//GEN-LAST:event_jButton8VerCategorias

    private void jButton2eliminar_productos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2eliminar_productos
        EliminarProducto add =new EliminarProducto (Menú, true);
        add.setVisible(true);
    }//GEN-LAST:event_jButton2eliminar_productos

    private void jButton3add_producto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3add_producto
        Agregar_producto add =new Agregar_producto (Menú, true);
        add.setVisible(true);
    }//GEN-LAST:event_jButton3add_producto

    private void jButton4add_subCategoria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4add_subCategoria
        Subcategoria add =new Subcategoria (Menú, true);
        add.setVisible(true);
    }//GEN-LAST:event_jButton4add_subCategoria

    private void jLabel5Salir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5Salir
        Menú.eliminar_de_tabbed();
    }//GEN-LAST:event_jLabel5Salir

    private void jButton6verTodoElStock(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6verTodoElStock
        VerStock add =new VerStock (Menú, true);
        add.setVisible(true);
    }//GEN-LAST:event_jButton6verTodoElStock


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
